name: build KSU kernel - OPPO Reno6 Pro
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 构建编译内核环境
      run: |
        sudo apt-get update
        sudo -E apt-get -y -qq install git make bc bison ccache openssl dos2unix zip kmod cpio flex libelf-dev curl libssl-dev libtfm-dev wget device-tree-compiler ca-certificates python3 python2 binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi
        
    - name: 下载 Gcc编译器
      run: |
          cd $HOME
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 aarch64-linux-android-4.9
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 arm-linux-androideabi-4.9
          
    - name: 构建编译内核环境
      run: |
          cd $HOME
          mkdir clang
              wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-release/clang-r383902.tar.gz
                tar -C clang/ -zxvf clang-r383902.tar.gz
                
    - name: 下载内核源码
      run: |
         cd $HOME
         git clone https://github.com/hanyu133341/android_kernel_oppo_mtk6893 --depth=1
         
    - name: 设置 Kernelsu
      run: |
         cd $HOME/android_kernel_oppo_mtk6893
         curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
         
    - name: 设置ccache缓存
      run: |
         hendrikmuhs/ccache-action@v1.2
         key: build-kernel-mido-kernel
         max-size: 5G
         
    - name: 开始编译内核
      run: |
        cd $HOME/android_kernel_oppo_mtk6893
        export KBUILD_BUILD_HOST=24
        export KBUILD_BUILD_USER=hanyu133341
          bash build_kernel.sh
          
    - name: 制作Anykernel3卡刷包
      run: |
        cd $HOME
        git clone https://github.com/osm0sis/AnyKernel3
        sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
        sed -i 's!block=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!block=auto;!g' AnyKernel3/anykernel.sh
        sed -i 's/is_slot_device=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
        cp android_kernel_oppo_mtk6893/out/arch/arm64/boot/Image.gz AnyKernel3/
        rm -rf AnyKernel3/.git* AnyKernel3/README.md
        
        - name: 上传 Anykernel3
         uses: actions/upload-artifact@v4
         with:
        name: OPPO Reno6 Pro安卓13-mtk6893内核-卡刷包
        cd $HOME
        path: AnyKernel3/*
    
    - name: 上传编译内核
      uses: actions/upload-artifact@v4
      with:
        name: mtk6893内核-Image.gz
         cd $HOME
        path: android_kernel_oppo_mtk6893/out/arch/arm64/boot/*

      
